<?php
header('Content-Type: application/json; charset=utf-8');
class AccountsViewProduct extends SugarView
{
 public function display()
 {
    global $db;
    $sqlSelect = "SELECT * FROM a_products";
    $result = $db->query($sqlSelect);  
    $array= [];
    while($row = $db->fetchByAssoc($result)){
        //Chuyển kết quả select sang dạng array
            $array[]=$row;
    }
    echo json_encode($array);
    $this->ss->assign("product_list", $array);
    parent::display(); // TODO: Change the autogenerated stub
 }
}
?>