<?php

class A_OrdersViewEdit extends ViewEdit
{
 public function display()
 {
    global $db;
    $sqlSelect = "SELECT * FROM a_products";
    $result = $db->query($sqlSelect);  
    $array= [];
    while($row = $db->fetchByAssoc($result)){
        //Chuyển kết quả select sang dạng array
        $array[]=$row;
    }
    $this->ss->assign("product_list", $array);
     //truyền giá trị của field ticker_symbol vào tpl      
    if(!empty($this->bean->order_id))
    {
      $order_id = $this->bean->order_id;
      $sqlSelect1 = " SELECT *, p.price as unit_price, o.price as total_price
                      FROM a_orderdetail as o, a_products as p, a_orders as od
                      WHERE o.order_id = '$order_id' AND o.product_id = p.product_id
                      AND od.order_id = o.order_id ";
      $result1 = $db->query($sqlSelect1);
      $array_orderdetail =[];
      $total_price =0;
      $total_discount=0;
      $temp_price=0;
      $i=0;
      while($row_fetch = $db->fetchByAssoc($result1))
      {

        $array_orderdetail[] = $row_fetch;
        $temp_price+=($array_orderdetail[$i]['unit_price']*$array_orderdetail[$i]['quantity']);
        $total_price+=($array_orderdetail[$i]['total_price']);
        $i++;
      }
      $this->ss->assign("order_detail",$array_orderdetail);
      $this->ss->assign("total_discount_order",$temp_price-$total_price);  
      $this->ss->assign("total_temp_price_order",$temp_price);  
      $this->ss->assign("order_id",$this->bean->order_id);  
      $this->ss->assign("order_total_price",$total_price);     

    }
    else
    {
      //dang trong action tao moi
      $sqlSelect2 = "SELECT order_id FROM a_orders ORDER BY order_id DESC";
      $row2 = $db->fetchOne($sqlSelect2);
      if(!empty($row2['order_id']))
      {
        $this->ss->assign("order_id",++$row2['order_id']);
      }
      else
      {
        $this->ss->assign("order_id",'HD001');

      }
    }
      // $this->ss->assign("order_id", );
         parent::display(); // TODO: Change the autogenerated stub
 }
}
?>