<?php

class A_OrdersViewEdit extends ViewEdit
{
 public function display()
 {
    global $db;
    $sqlSelect = "SELECT * FROM a_products";
    $result = $db->query($sqlSelect);  
    $array= [];
    while($row = $db->fetchByAssoc($result)){
        //Chuyển kết quả select sang dạng array
        $array[]=$row;
    }
    $this->ss->assign("product_list", $array);
     //truyền giá trị của field ticker_symbol vào tpl      
     if(isset($this->bean->order_id))
     {
        $this->ss->assign("ABC", $this->bean->order_id);
     }
     else
     {
        $this->ss->assign("ABC","");
     }
         parent::display(); // TODO: Change the autogenerated stub
 }
}
?>